infra:
        #$(RUN_DOCK) "remotestate"
        #$(RUN_DOCK) "terraform init \
	terraform init \
	terraform plan
        #&& terraform apply -auto-approve \
        #&& terraform output"
	#terraform output
destroy:
        #$(RUN_DOCK) "terraform destroy -auto-approve"
